### ISSUE TITLE
Error file

### ISSUE THREAD

**Issue by AuroreAttina** [JamesGallant/ProVision#13]
[proteinGroups.txt](https://github.com/JamesGallant/ProVision/files/6770916/proteinGroups.txt)

Hi,

I found your platform, and I think it's a great tool to analyze mass-spectrometry data. I already test it with your test data. But when I tried to download my data, I always have an error: "Certain key columns were not detected, are you sure the file is correct?".
I compared your text file with my text file and I don't find the difference. I joint my proteinGroups file, if you would check it.

Can you help me?

Best regards,

Aurore ATTINA

**Comment by MardahlM** [comment]
I get exactly the same error. This occurs after I took rowmeans() of technical replicate columns in R before uploading into Provision. It reports "Protein IDs column not detected, is this a MaxQuant file?" . How can I otherwise take means of technical replicates in the shiny app. IMO, I can't show technical replicates in PCA and heatmaps for publications. Please advice:-) Looking forward to your reply. Nonetheless, thanks for a great tool! Cheers

**Comment by JamesGallant** [comment]
@AuroreAttina So sorry I never got back to you, I thought I already did over email, I'm not sure it would be relevant anymore but this error happens when you are missing key columns used for filtering. Its important to use the file directly from MQ. Specifically it looks for potential contaminants, reverse database hits and site modifications.
